apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: nginx
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD 
      value: "pass"
    - name: MYSQL_DATABASE 
      value: "dbb"
    ports:
    - containerPort: 3306
