apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports: 
  - protocol: TCP
    port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels: 
    app: service3
spec:
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: iwantm/rng:service3
        ports:
        - containerPort: 5002