apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports: 
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels: 
    app: service2
spec:
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: iwantm/rng:service2
        ports:
        - containerPort: 5001