apiVersion: v1
kind: Service
metadata:
  name: event-tracker
spec:
  selector:
    app: event-tracker
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-tracker
  labels: 
    app: event-tracker
spec:
  selector:
    matchLabels:
      app: event-tracker
  template:
    metadata:
      labels:
        app: event-tracker
    spec:
      containers:
      - name: event-tracker
        image: iwantm/qaeventtrack:tagname
        env:
        - name: DATABASE_URI_PROJECT 
          valueFrom:
            secretKeyRef:
              name: db-uri
              key: uri
        ports:
        - containerPort: 5000