apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
  pass: {{pass}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-name
type: Opaque
stringData:
  db-name: {{db-name}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-uri
type: Opaque
stringData:
  uri: "mysql+pymysql://root:{{pass}}@mysql:3306/{{db-name}}"
 